// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

// Name: AddCollectionItemBody
export const AddCollectionItemBody = z.object({
  // Name: AddCollectionItemBody.mediaId
  "mediaId": z.string(),
  // Name: AddCollectionItemBody.name
  "name": z.string(),
  // Name: AddCollectionItemBody.searchSlug
  "searchSlug": z.string(),
  // Name: AddCollectionItemBody.position
  "position": z.number(),
});
export type AddCollectionItemBody = z.infer<typeof AddCollectionItemBody>;

// Name: AddPart
export const AddPart = z.object({
  // Name: AddPart.index
  "index": z.number(),
});
export type AddPart = z.infer<typeof AddPart>;

// Name: AddPartBody
export const AddPartBody = z.object({
  // Name: AddPartBody.index
  "index": z.number(),
  // Name: AddPartBody.name
  "name": z.string(),
  // Name: AddPartBody.releaseDate
  "releaseDate": z.string(),
});
export type AddPartBody = z.infer<typeof AddPartBody>;

// Name: ApiToken
export const ApiToken = z.object({
  // Name: ApiToken.id
  "id": z.string(),
  // Name: ApiToken.name
  "name": z.string(),
});
export type ApiToken = z.infer<typeof ApiToken>;

// Name: ChangePasswordBody
export const ChangePasswordBody = z.object({
  // Name: ChangePasswordBody.currentPassword
  "currentPassword": z.string(),
  // Name: ChangePasswordBody.newPassword
  "newPassword": z.string(),
  // Name: ChangePasswordBody.newPasswordConfirm
  "newPasswordConfirm": z.string(),
});
export type ChangePasswordBody = z.infer<typeof ChangePasswordBody>;

// Name: ProviderValue
export const ProviderValue = z.object({
  // Name: ProviderValue.name
  "name": z.string(),
  // Name: ProviderValue.displayName
  "displayName": z.string(),
  // Name: ProviderValue.value
  "value": z.string(),
});
export type ProviderValue = z.infer<typeof ProviderValue>;

// Name: Collection
export const Collection = z.object({
  // Name: Collection.id
  "id": z.string(),
  // Name: Collection.type
  "type": z.string(),
  // Name: Collection.name
  "name": z.string(),
  // Name: Collection.coverUrl
  "coverUrl": z.string().nullable(),
  // Name: Collection.logoUrl
  "logoUrl": z.string().nullable(),
  // Name: Collection.bannerUrl
  "bannerUrl": z.string().nullable(),
  // Name: Collection.defaultProvider
  "defaultProvider": z.string().nullable(),
  // Name: Collection.providers
  "providers": z.array(ProviderValue),
});
export type Collection = z.infer<typeof Collection>;

// Name: MediaUser
export const MediaUser = z.object({
  // Name: MediaUser.hasData
  "hasData": z.boolean(),
  // Name: MediaUser.list
  "list": z.string(),
  // Name: MediaUser.score
  "score": z.number().nullable(),
  // Name: MediaUser.currentPart
  "currentPart": z.number().nullable(),
  // Name: MediaUser.revisitCount
  "revisitCount": z.number().nullable(),
  // Name: MediaUser.isRevisiting
  "isRevisiting": z.boolean(),
});
export type MediaUser = z.infer<typeof MediaUser>;

// Name: CollectionItem
export const CollectionItem = z.object({
  // Name: CollectionItem.collectionId
  "collectionId": z.string(),
  // Name: CollectionItem.mediaId
  "mediaId": z.string(),
  // Name: CollectionItem.collectionName
  "collectionName": z.string(),
  // Name: CollectionItem.searchSlug
  "searchSlug": z.string(),
  // Name: CollectionItem.position
  "position": z.number(),
  // Name: CollectionItem.title
  "title": z.string(),
  // Name: CollectionItem.description
  "description": z.string().nullable(),
  // Name: CollectionItem.mediaType
  "mediaType": z.string(),
  // Name: CollectionItem.score
  "score": z.number().nullable(),
  // Name: CollectionItem.status
  "status": z.string(),
  // Name: CollectionItem.rating
  "rating": z.string(),
  // Name: CollectionItem.partCount
  "partCount": z.number(),
  // Name: CollectionItem.airingSeason
  "airingSeason": z.string().nullable(),
  // Name: CollectionItem.startDate
  "startDate": z.string().nullable(),
  // Name: CollectionItem.endDate
  "endDate": z.string().nullable(),
  // Name: CollectionItem.creators
  "creators": z.array(z.string()),
  // Name: CollectionItem.tags
  "tags": z.array(z.string()),
  // Name: CollectionItem.coverUrl
  "coverUrl": z.string().nullable(),
  // Name: CollectionItem.logoUrl
  "logoUrl": z.string().nullable(),
  // Name: CollectionItem.bannerUrl
  "bannerUrl": z.string().nullable(),
  // Name: CollectionItem.user
  "user": MediaUser.nullable().optional(),
});
export type CollectionItem = z.infer<typeof CollectionItem>;

// Name: CreateApiToken
export const CreateApiToken = z.object({
  // Name: CreateApiToken.token
  "token": z.string(),
});
export type CreateApiToken = z.infer<typeof CreateApiToken>;

// Name: CreateApiTokenBody
export const CreateApiTokenBody = z.object({
  // Name: CreateApiTokenBody.name
  "name": z.string(),
});
export type CreateApiTokenBody = z.infer<typeof CreateApiTokenBody>;

// Name: CreateCollection
export const CreateCollection = z.object({
  // Name: CreateCollection.id
  "id": z.string(),
});
export type CreateCollection = z.infer<typeof CreateCollection>;

// Name: CreateCollectionBody
export const CreateCollectionBody = z.object({
  // Name: CreateCollectionBody.type
  "type": z.string(),
  // Name: CreateCollectionBody.name
  "name": z.string(),
  // Name: CreateCollectionBody.coverUrl
  "coverUrl": z.string(),
  // Name: CreateCollectionBody.bannerUrl
  "bannerUrl": z.string(),
  // Name: CreateCollectionBody.logoUrl
  "logoUrl": z.string(),
});
export type CreateCollectionBody = z.infer<typeof CreateCollectionBody>;

// Name: CreateFolder
export const CreateFolder = z.object({
  // Name: CreateFolder.id
  "id": z.string(),
});
export type CreateFolder = z.infer<typeof CreateFolder>;

// Name: CreateFolderBody
export const CreateFolderBody = z.object({
  // Name: CreateFolderBody.name
  "name": z.string(),
  // Name: CreateFolderBody.coverUrl
  "coverUrl": z.string(),
});
export type CreateFolderBody = z.infer<typeof CreateFolderBody>;

// Name: CreateMedia
export const CreateMedia = z.object({
  // Name: CreateMedia.id
  "id": z.string(),
});
export type CreateMedia = z.infer<typeof CreateMedia>;

// Name: CreateMediaBody
export const CreateMediaBody = z.object({
  // Name: CreateMediaBody.type
  "type": z.string(),
  // Name: CreateMediaBody.title
  "title": z.string(),
  // Name: CreateMediaBody.description
  "description": z.string(),
  // Name: CreateMediaBody.score
  "score": z.number(),
  // Name: CreateMediaBody.status
  "status": z.string(),
  // Name: CreateMediaBody.rating
  "rating": z.string(),
  // Name: CreateMediaBody.airingSeason
  "airingSeason": z.string(),
  // Name: CreateMediaBody.startDate
  "startDate": z.string(),
  // Name: CreateMediaBody.endDate
  "endDate": z.string(),
  // Name: CreateMediaBody.partCount
  "partCount": z.number(),
  // Name: CreateMediaBody.coverUrl
  "coverUrl": z.string(),
  // Name: CreateMediaBody.bannerUrl
  "bannerUrl": z.string(),
  // Name: CreateMediaBody.logoUrl
  "logoUrl": z.string(),
  // Name: CreateMediaBody.tags
  "tags": z.array(z.string()),
  // Name: CreateMediaBody.creators
  "creators": z.array(z.string()),
});
export type CreateMediaBody = z.infer<typeof CreateMediaBody>;

// Name: EditCollectionBody
export const EditCollectionBody = z.object({
  // Name: EditCollectionBody.type
  "type": z.string().nullable().optional(),
  // Name: EditCollectionBody.name
  "name": z.string().nullable().optional(),
  // Name: EditCollectionBody.coverUrl
  "coverUrl": z.string().nullable().optional(),
  // Name: EditCollectionBody.bannerUrl
  "bannerUrl": z.string().nullable().optional(),
  // Name: EditCollectionBody.logoUrl
  "logoUrl": z.string().nullable().optional(),
});
export type EditCollectionBody = z.infer<typeof EditCollectionBody>;

// Name: EditCollectionItemBody
export const EditCollectionItemBody = z.object({
  // Name: EditCollectionItemBody.name
  "name": z.string().nullable().optional(),
  // Name: EditCollectionItemBody.searchSlug
  "searchSlug": z.string().nullable().optional(),
  // Name: EditCollectionItemBody.position
  "position": z.number().nullable().optional(),
});
export type EditCollectionItemBody = z.infer<typeof EditCollectionItemBody>;

// Name: EditFolderBody
export const EditFolderBody = z.object({
  // Name: EditFolderBody.name
  "name": z.string().nullable().optional(),
  // Name: EditFolderBody.coverUrl
  "coverUrl": z.string().nullable().optional(),
});
export type EditFolderBody = z.infer<typeof EditFolderBody>;

// Name: EditMediaBody
export const EditMediaBody = z.object({
  // Name: EditMediaBody.type
  "type": z.string().nullable().optional(),
  // Name: EditMediaBody.title
  "title": z.string().nullable().optional(),
  // Name: EditMediaBody.description
  "description": z.string().nullable().optional(),
  // Name: EditMediaBody.score
  "score": z.number().nullable().optional(),
  // Name: EditMediaBody.status
  "status": z.string().nullable().optional(),
  // Name: EditMediaBody.rating
  "rating": z.string().nullable().optional(),
  // Name: EditMediaBody.airingSeason
  "airingSeason": z.string().nullable().optional(),
  // Name: EditMediaBody.startDate
  "startDate": z.string().nullable().optional(),
  // Name: EditMediaBody.endDate
  "endDate": z.string().nullable().optional(),
  // Name: EditMediaBody.coverUrl
  "coverUrl": z.string().nullable().optional(),
  // Name: EditMediaBody.bannerUrl
  "bannerUrl": z.string().nullable().optional(),
  // Name: EditMediaBody.logoUrl
  "logoUrl": z.string().nullable().optional(),
  // Name: EditMediaBody.tags
  "tags": z.array(z.string()).nullable().optional(),
  // Name: EditMediaBody.creators
  "creators": z.array(z.string()).nullable().optional(),
});
export type EditMediaBody = z.infer<typeof EditMediaBody>;

// Name: EditPartBody
export const EditPartBody = z.object({
  // Name: EditPartBody.name
  "name": z.string().nullable().optional(),
  // Name: EditPartBody.releaseDate
  "releaseDate": z.string().nullable().optional(),
});
export type EditPartBody = z.infer<typeof EditPartBody>;

// Name: Folder
export const Folder = z.object({
  // Name: Folder.id
  "id": z.string(),
  // Name: Folder.userId
  "userId": z.string(),
  // Name: Folder.name
  "name": z.string(),
  // Name: Folder.itemCount
  "itemCount": z.number(),
  // Name: Folder.coverUrl
  "coverUrl": z.string().nullable(),
});
export type Folder = z.infer<typeof Folder>;

// Name: FolderItem
export const FolderItem = z.object({
  // Name: FolderItem.folderId
  "folderId": z.string(),
  // Name: FolderItem.mediaId
  "mediaId": z.string(),
  // Name: FolderItem.position
  "position": z.number(),
  // Name: FolderItem.title
  "title": z.string(),
  // Name: FolderItem.description
  "description": z.string().nullable(),
  // Name: FolderItem.mediaType
  "mediaType": z.string(),
  // Name: FolderItem.score
  "score": z.number().nullable(),
  // Name: FolderItem.status
  "status": z.string(),
  // Name: FolderItem.rating
  "rating": z.string(),
  // Name: FolderItem.partCount
  "partCount": z.number(),
  // Name: FolderItem.airingSeason
  "airingSeason": z.string().nullable(),
  // Name: FolderItem.startDate
  "startDate": z.string().nullable(),
  // Name: FolderItem.endDate
  "endDate": z.string().nullable(),
  // Name: FolderItem.creators
  "creators": z.array(z.string()),
  // Name: FolderItem.tags
  "tags": z.array(z.string()),
  // Name: FolderItem.coverUrl
  "coverUrl": z.string().nullable(),
  // Name: FolderItem.logoUrl
  "logoUrl": z.string().nullable(),
  // Name: FolderItem.bannerUrl
  "bannerUrl": z.string().nullable(),
  // Name: FolderItem.user
  "user": MediaUser.nullable().optional(),
});
export type FolderItem = z.infer<typeof FolderItem>;

// Name: GetAllApiTokens
export const GetAllApiTokens = z.object({
  // Name: GetAllApiTokens.tokens
  "tokens": z.array(ApiToken),
});
export type GetAllApiTokens = z.infer<typeof GetAllApiTokens>;

// Name: GetCollectionById
export const GetCollectionById = z.object({
  // Name: GetCollectionById.id
  "id": z.string(),
  // Name: GetCollectionById.type
  "type": z.string(),
  // Name: GetCollectionById.name
  "name": z.string(),
  // Name: GetCollectionById.coverUrl
  "coverUrl": z.string().nullable(),
  // Name: GetCollectionById.logoUrl
  "logoUrl": z.string().nullable(),
  // Name: GetCollectionById.bannerUrl
  "bannerUrl": z.string().nullable(),
  // Name: GetCollectionById.defaultProvider
  "defaultProvider": z.string().nullable(),
  // Name: GetCollectionById.providers
  "providers": z.array(ProviderValue),
});
export type GetCollectionById = z.infer<typeof GetCollectionById>;

// Name: GetCollectionItems
export const GetCollectionItems = z.object({
  // Name: GetCollectionItems.items
  "items": z.array(CollectionItem),
});
export type GetCollectionItems = z.infer<typeof GetCollectionItems>;

// Name: Page
export const Page = z.object({
  // Name: Page.page
  "page": z.number(),
  // Name: Page.perPage
  "perPage": z.number(),
  // Name: Page.totalItems
  "totalItems": z.number(),
  // Name: Page.totalPages
  "totalPages": z.number(),
});
export type Page = z.infer<typeof Page>;

// Name: GetCollections
export const GetCollections = z.object({
  // Name: GetCollections.page
  "page": Page,
  // Name: GetCollections.collections
  "collections": z.array(Collection),
});
export type GetCollections = z.infer<typeof GetCollections>;

// Name: GetFolderById
export const GetFolderById = z.object({
  // Name: GetFolderById.id
  "id": z.string(),
  // Name: GetFolderById.userId
  "userId": z.string(),
  // Name: GetFolderById.name
  "name": z.string(),
  // Name: GetFolderById.itemCount
  "itemCount": z.number(),
  // Name: GetFolderById.coverUrl
  "coverUrl": z.string().nullable(),
});
export type GetFolderById = z.infer<typeof GetFolderById>;

// Name: GetFolderItems
export const GetFolderItems = z.object({
  // Name: GetFolderItems.items
  "items": z.array(FolderItem),
});
export type GetFolderItems = z.infer<typeof GetFolderItems>;

// Name: GetFolders
export const GetFolders = z.object({
  // Name: GetFolders.folders
  "folders": z.array(Folder),
});
export type GetFolders = z.infer<typeof GetFolders>;

// Name: GetMe
export const GetMe = z.object({
  // Name: GetMe.id
  "id": z.string(),
  // Name: GetMe.username
  "username": z.string(),
  // Name: GetMe.role
  "role": z.string(),
  // Name: GetMe.displayName
  "displayName": z.string(),
});
export type GetMe = z.infer<typeof GetMe>;

// Name: MediaRelease
export const MediaRelease = z.object({
  // Name: MediaRelease.releaseType
  "releaseType": z.string(),
  // Name: MediaRelease.startDate
  "startDate": z.string(),
  // Name: MediaRelease.numExpectedParts
  "numExpectedParts": z.number(),
  // Name: MediaRelease.partOffset
  "partOffset": z.number(),
  // Name: MediaRelease.intervalDays
  "intervalDays": z.number(),
  // Name: MediaRelease.delayDays
  "delayDays": z.number(),
  // Name: MediaRelease.status
  "status": z.string(),
  // Name: MediaRelease.currentPart
  "currentPart": z.number(),
  // Name: MediaRelease.nextAiring
  "nextAiring": z.string().nullable(),
});
export type MediaRelease = z.infer<typeof MediaRelease>;

// Name: Media
export const Media = z.object({
  // Name: Media.id
  "id": z.string(),
  // Name: Media.title
  "title": z.string(),
  // Name: Media.description
  "description": z.string().nullable(),
  // Name: Media.type
  "type": z.string(),
  // Name: Media.score
  "score": z.number().nullable(),
  // Name: Media.status
  "status": z.string(),
  // Name: Media.rating
  "rating": z.string(),
  // Name: Media.partCount
  "partCount": z.number(),
  // Name: Media.airingSeason
  "airingSeason": z.string().nullable(),
  // Name: Media.startDate
  "startDate": z.string().nullable(),
  // Name: Media.endDate
  "endDate": z.string().nullable(),
  // Name: Media.creators
  "creators": z.array(z.string()),
  // Name: Media.tags
  "tags": z.array(z.string()),
  // Name: Media.coverUrl
  "coverUrl": z.string().nullable(),
  // Name: Media.bannerUrl
  "bannerUrl": z.string().nullable(),
  // Name: Media.logoUrl
  "logoUrl": z.string().nullable(),
  // Name: Media.defaultProvider
  "defaultProvider": z.string().nullable(),
  // Name: Media.providers
  "providers": z.array(ProviderValue),
  // Name: Media.user
  "user": MediaUser.nullable().optional(),
  // Name: Media.release
  "release": MediaRelease.nullable(),
});
export type Media = z.infer<typeof Media>;

// Name: GetMedia
export const GetMedia = z.object({
  // Name: GetMedia.page
  "page": Page,
  // Name: GetMedia.media
  "media": z.array(Media),
});
export type GetMedia = z.infer<typeof GetMedia>;

// Name: GetMediaById
export const GetMediaById = z.object({
  // Name: GetMediaById.id
  "id": z.string(),
  // Name: GetMediaById.title
  "title": z.string(),
  // Name: GetMediaById.description
  "description": z.string().nullable(),
  // Name: GetMediaById.type
  "type": z.string(),
  // Name: GetMediaById.score
  "score": z.number().nullable(),
  // Name: GetMediaById.status
  "status": z.string(),
  // Name: GetMediaById.rating
  "rating": z.string(),
  // Name: GetMediaById.partCount
  "partCount": z.number(),
  // Name: GetMediaById.airingSeason
  "airingSeason": z.string().nullable(),
  // Name: GetMediaById.startDate
  "startDate": z.string().nullable(),
  // Name: GetMediaById.endDate
  "endDate": z.string().nullable(),
  // Name: GetMediaById.creators
  "creators": z.array(z.string()),
  // Name: GetMediaById.tags
  "tags": z.array(z.string()),
  // Name: GetMediaById.coverUrl
  "coverUrl": z.string().nullable(),
  // Name: GetMediaById.bannerUrl
  "bannerUrl": z.string().nullable(),
  // Name: GetMediaById.logoUrl
  "logoUrl": z.string().nullable(),
  // Name: GetMediaById.defaultProvider
  "defaultProvider": z.string().nullable(),
  // Name: GetMediaById.providers
  "providers": z.array(ProviderValue),
  // Name: GetMediaById.user
  "user": MediaUser.nullable().optional(),
  // Name: GetMediaById.release
  "release": MediaRelease.nullable(),
});
export type GetMediaById = z.infer<typeof GetMediaById>;

// Name: MediaPart
export const MediaPart = z.object({
  // Name: MediaPart.index
  "index": z.number(),
  // Name: MediaPart.mediaId
  "mediaId": z.string(),
  // Name: MediaPart.name
  "name": z.string(),
  // Name: MediaPart.releaseDate
  "releaseDate": z.string().nullable(),
});
export type MediaPart = z.infer<typeof MediaPart>;

// Name: GetMediaParts
export const GetMediaParts = z.object({
  // Name: GetMediaParts.parts
  "parts": z.array(MediaPart),
});
export type GetMediaParts = z.infer<typeof GetMediaParts>;

// Name: ProviderSearchResult
export const ProviderSearchResult = z.object({
  // Name: ProviderSearchResult.providerName
  "providerName": z.string(),
  // Name: ProviderSearchResult.providerId
  "providerId": z.string(),
  // Name: ProviderSearchResult.title
  "title": z.string(),
  // Name: ProviderSearchResult.imageUrl
  "imageUrl": z.string(),
});
export type ProviderSearchResult = z.infer<typeof ProviderSearchResult>;

// Name: GetProviderSearch
export const GetProviderSearch = z.object({
  // Name: GetProviderSearch.searchResults
  "searchResults": z.array(ProviderSearchResult),
});
export type GetProviderSearch = z.infer<typeof GetProviderSearch>;

// Name: ProviderSupports
export const ProviderSupports = z.object({
  // Name: ProviderSupports.getMedia
  "getMedia": z.boolean(),
  // Name: ProviderSupports.searchMedia
  "searchMedia": z.boolean(),
  // Name: ProviderSupports.getCollection
  "getCollection": z.boolean(),
  // Name: ProviderSupports.searchCollection
  "searchCollection": z.boolean(),
});
export type ProviderSupports = z.infer<typeof ProviderSupports>;

// Name: Provider
export const Provider = z.object({
  // Name: Provider.name
  "name": z.string(),
  // Name: Provider.displayName
  "displayName": z.string(),
  // Name: Provider.supports
  "supports": ProviderSupports,
});
export type Provider = z.infer<typeof Provider>;

// Name: GetProviders
export const GetProviders = z.object({
  // Name: GetProviders.providers
  "providers": z.array(Provider),
});
export type GetProviders = z.infer<typeof GetProviders>;

// Name: GetSystemInfo
export const GetSystemInfo = z.object({
  // Name: GetSystemInfo.version
  "version": z.string(),
});
export type GetSystemInfo = z.infer<typeof GetSystemInfo>;

// Name: GetUser
export const GetUser = z.object({
  // Name: GetUser.id
  "id": z.string(),
  // Name: GetUser.username
  "username": z.string(),
  // Name: GetUser.displayName
  "displayName": z.string(),
});
export type GetUser = z.infer<typeof GetUser>;

// Name: Stat
export const Stat = z.object({
  // Name: Stat.name
  "name": z.string(),
  // Name: Stat.value
  "value": z.number(),
});
export type Stat = z.infer<typeof Stat>;

// Name: MainStat
export const MainStat = z.object({
  // Name: MainStat.main
  "main": Stat,
  // Name: MainStat.sub
  "sub": z.array(Stat),
});
export type MainStat = z.infer<typeof MainStat>;

// Name: GetUserStats
export const GetUserStats = z.object({
  // Name: GetUserStats.all
  "all": MainStat,
  // Name: GetUserStats.completed
  "completed": MainStat,
  // Name: GetUserStats.inProgress
  "inProgress": MainStat,
  // Name: GetUserStats.onHold
  "onHold": MainStat,
  // Name: GetUserStats.dropped
  "dropped": MainStat,
  // Name: GetUserStats.backlog
  "backlog": MainStat,
});
export type GetUserStats = z.infer<typeof GetUserStats>;

// Name: PartBody
export const PartBody = z.object({
  // Name: PartBody.name
  "name": z.string(),
  // Name: PartBody.releaseDate
  "releaseDate": z.string(),
});
export type PartBody = z.infer<typeof PartBody>;

// Name: PostProviderImportCollectionsBody
export const PostProviderImportCollectionsBody = z.object({
  // Name: PostProviderImportCollectionsBody.ids
  "ids": z.array(z.string()),
});
export type PostProviderImportCollectionsBody = z.infer<typeof PostProviderImportCollectionsBody>;

// Name: PostProviderImportMediaBody
export const PostProviderImportMediaBody = z.object({
  // Name: PostProviderImportMediaBody.ids
  "ids": z.array(z.string()),
});
export type PostProviderImportMediaBody = z.infer<typeof PostProviderImportMediaBody>;

// Name: ProviderCollectionUpdateBody
export const ProviderCollectionUpdateBody = z.object({
  // Name: ProviderCollectionUpdateBody.replaceImages
  "replaceImages": z.boolean().optional(),
});
export type ProviderCollectionUpdateBody = z.infer<typeof ProviderCollectionUpdateBody>;

// Name: ProviderMediaUpdateBody
export const ProviderMediaUpdateBody = z.object({
  // Name: ProviderMediaUpdateBody.replaceImages
  "replaceImages": z.boolean().optional(),
  // Name: ProviderMediaUpdateBody.overrideParts
  "overrideParts": z.boolean().optional(),
  // Name: ProviderMediaUpdateBody.setRelease
  "setRelease": z.boolean().optional(),
});
export type ProviderMediaUpdateBody = z.infer<typeof ProviderMediaUpdateBody>;

// Name: SetMediaReleaseBody
export const SetMediaReleaseBody = z.object({
  // Name: SetMediaReleaseBody.releaseType
  "releaseType": z.string(),
  // Name: SetMediaReleaseBody.startDate
  "startDate": z.string(),
  // Name: SetMediaReleaseBody.numExpectedParts
  "numExpectedParts": z.number(),
  // Name: SetMediaReleaseBody.partOffset
  "partOffset": z.number(),
  // Name: SetMediaReleaseBody.intervalDays
  "intervalDays": z.number(),
  // Name: SetMediaReleaseBody.delayDays
  "delayDays": z.number(),
});
export type SetMediaReleaseBody = z.infer<typeof SetMediaReleaseBody>;

// Name: SetMediaUserData
export const SetMediaUserData = z.object({
  // Name: SetMediaUserData.list
  "list": z.string().nullable().optional(),
  // Name: SetMediaUserData.score
  "score": z.number().nullable().optional(),
  // Name: SetMediaUserData.currentPart
  "currentPart": z.number().nullable().optional(),
  // Name: SetMediaUserData.revisitCount
  "revisitCount": z.number().nullable().optional(),
  // Name: SetMediaUserData.isRevisiting
  "isRevisiting": z.boolean().nullable().optional(),
});
export type SetMediaUserData = z.infer<typeof SetMediaUserData>;

// Name: SetPartsBody
export const SetPartsBody = z.object({
  // Name: SetPartsBody.parts
  "parts": z.array(PartBody),
});
export type SetPartsBody = z.infer<typeof SetPartsBody>;

// Name: Signin
export const Signin = z.object({
  // Name: Signin.token
  "token": z.string(),
});
export type Signin = z.infer<typeof Signin>;

// Name: SigninBody
export const SigninBody = z.object({
  // Name: SigninBody.username
  "username": z.string(),
  // Name: SigninBody.password
  "password": z.string(),
});
export type SigninBody = z.infer<typeof SigninBody>;

// Name: Signup
export const Signup = z.object({
  // Name: Signup.id
  "id": z.string(),
  // Name: Signup.username
  "username": z.string(),
});
export type Signup = z.infer<typeof Signup>;

// Name: SignupBody
export const SignupBody = z.object({
  // Name: SignupBody.username
  "username": z.string(),
  // Name: SignupBody.password
  "password": z.string(),
  // Name: SignupBody.passwordConfirm
  "passwordConfirm": z.string(),
});
export type SignupBody = z.infer<typeof SignupBody>;

// Name: UpdateUserSettingsBody
export const UpdateUserSettingsBody = z.object({
  // Name: UpdateUserSettingsBody.displayName
  "displayName": z.string().nullable().optional(),
});
export type UpdateUserSettingsBody = z.infer<typeof UpdateUserSettingsBody>;

// Name: UserData
export const UserData = z.object({
  // Name: UserData.id
  "id": z.string(),
  // Name: UserData.username
  "username": z.string(),
  // Name: UserData.displayName
  "displayName": z.string(),
});
export type UserData = z.infer<typeof UserData>;

