// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api

type GetUser struct {
	Id string `json:"id"`
	Username string `json:"username"`
	DisplayName *string `json:"displayName,omitempty"`
}

type MediaUser struct {
	HasData bool `json:"hasData"`
	List string `json:"list"`
	Score *int `json:"score,omitempty"`
	CurrentPart *int `json:"currentPart,omitempty"`
	RevisitCount *int `json:"revisitCount,omitempty"`
	IsRevisiting bool `json:"isRevisiting"`
}

type PartBody struct {
	Name string `json:"name"`
}

type SetPartsBody struct {
	Parts []PartBody `json:"parts"`
}

type SigninBody struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type GetMe struct {
	Id string `json:"id"`
	Username string `json:"username"`
	Role string `json:"role"`
	DisplayName string `json:"displayName"`
}

type CreateApiToken struct {
	Token string `json:"token"`
}

type CreateApiTokenBody struct {
	Name string `json:"name"`
}

type CreateCollection struct {
	Id string `json:"id"`
}

type UserData struct {
	Id string `json:"id"`
	Username string `json:"username"`
	DisplayName *string `json:"displayName,omitempty"`
}

type MediaPart struct {
	Index int `json:"index"`
	MediaId string `json:"mediaId"`
	Name string `json:"name"`
}

type CreateCollectionBody struct {
	CollectionType string `json:"collectionType"`
	Name string `json:"name"`
}

type AddCollectionItemBody struct {
	MediaId string `json:"mediaId"`
	Name string `json:"name"`
	SearchSlug string `json:"searchSlug"`
	Order int `json:"order"`
}

type GetNotificationById struct {
	Id string `json:"id"`
	UserId string `json:"userId"`
	NotificationType string `json:"notificationType"`
	Title string `json:"title"`
	Message string `json:"message"`
	Metadata map[string]string `json:"metadata"`
	IsRead bool `json:"isRead"`
}

type Signup struct {
	Id string `json:"id"`
	Username string `json:"username"`
}

type ChangePasswordBody struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword string `json:"newPassword"`
	NewPasswordConfirm string `json:"newPasswordConfirm"`
}

type GetMediaById struct {
	Id string `json:"id"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	TmdbId string `json:"tmdbId"`
	ImdbId string `json:"imdbId"`
	MalId string `json:"malId"`
	AnilistId string `json:"anilistId"`
	MediaType string `json:"mediaType"`
	Score *float32 `json:"score,omitempty"`
	Status string `json:"status"`
	Rating string `json:"rating"`
	PartCount int `json:"partCount"`
	AiringSeason *string `json:"airingSeason,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	Creators []string `json:"creators"`
	Tags []string `json:"tags"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	User *MediaUser `json:"user,omitempty"`
}

type GetMediaParts struct {
	Parts []MediaPart `json:"parts"`
}

type CreateMedia struct {
	Id string `json:"id"`
}

type CreateMediaBody struct {
	MediaType string `json:"mediaType"`
	TmdbId string `json:"tmdbId"`
	ImdbId string `json:"imdbId"`
	MalId string `json:"malId"`
	AnilistId string `json:"anilistId"`
	Title string `json:"title"`
	Description string `json:"description"`
	Score float32 `json:"score"`
	Status string `json:"status"`
	Rating string `json:"rating"`
	AiringSeason string `json:"airingSeason"`
	StartDate string `json:"startDate"`
	EndDate string `json:"endDate"`
	PartCount int `json:"partCount"`
	CoverUrl string `json:"coverUrl"`
	BannerUrl string `json:"bannerUrl"`
	LogoUrl string `json:"logoUrl"`
	Tags []string `json:"tags"`
	Creators []string `json:"creators"`
	CollectionId string `json:"collectionId"`
	CollectionName string `json:"collectionName"`
}

type AddPart struct {
	Index int `json:"index"`
}

type GetCollectionById struct {
	Id string `json:"id"`
	CollectionType string `json:"collectionType"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	Name string `json:"name"`
}

type ApiToken struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type Page struct {
	Page int `json:"page"`
	PerPage int `json:"perPage"`
	TotalItems int `json:"totalItems"`
	TotalPages int `json:"totalPages"`
}

type Collection struct {
	Id string `json:"id"`
	CollectionType string `json:"collectionType"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	Name string `json:"name"`
}

type CollectionItem struct {
	CollectionId string `json:"collectionId"`
	MediaId string `json:"mediaId"`
	CollectionName string `json:"collectionName"`
	SearchSlug string `json:"searchSlug"`
	Order int `json:"order"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	MediaType string `json:"mediaType"`
	Score *float32 `json:"score,omitempty"`
	Status string `json:"status"`
	Rating string `json:"rating"`
	PartCount int `json:"partCount"`
	AiringSeason *string `json:"airingSeason,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	Creators []string `json:"creators"`
	Tags []string `json:"tags"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	User *MediaUser `json:"user,omitempty"`
}

type GetCollectionItems struct {
	Items []CollectionItem `json:"items"`
}

type SignupBody struct {
	Username string `json:"username"`
	Password string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
}

type EditPartBody struct {
	Name *string `json:"name,omitempty"`
}

type GetCollections struct {
	Page Page `json:"page"`
	Collections []Collection `json:"collections"`
}

type ProviderMyAnimeListAnime struct {
	MalId string `json:"malId"`
	MediaType string `json:"mediaType"`
	Title string `json:"title"`
	TitleEnglish string `json:"titleEnglish"`
	Description string `json:"description"`
	Score *float32 `json:"score,omitempty"`
	Status string `json:"status"`
	Rating string `json:"rating"`
	AiringSeason string `json:"airingSeason"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	Studios []string `json:"studios"`
	Tags []string `json:"tags"`
	CoverImageUrl string `json:"coverImageUrl"`
	EpisodeCount *int `json:"episodeCount,omitempty"`
	UsingCache bool `json:"usingCache"`
}

type Notification struct {
	Id string `json:"id"`
	UserId string `json:"userId"`
	NotificationType string `json:"notificationType"`
	Title string `json:"title"`
	Message string `json:"message"`
	Metadata map[string]string `json:"metadata"`
	IsRead bool `json:"isRead"`
}

type Signin struct {
	Token string `json:"token"`
}

type GetAllApiTokens struct {
	Tokens []ApiToken `json:"tokens"`
}

type Media struct {
	Id string `json:"id"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	TmdbId string `json:"tmdbId"`
	ImdbId string `json:"imdbId"`
	MalId string `json:"malId"`
	AnilistId string `json:"anilistId"`
	MediaType string `json:"mediaType"`
	Score *float32 `json:"score,omitempty"`
	Status string `json:"status"`
	Rating string `json:"rating"`
	PartCount int `json:"partCount"`
	AiringSeason *string `json:"airingSeason,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	Creators []string `json:"creators"`
	Tags []string `json:"tags"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	User *MediaUser `json:"user,omitempty"`
}

type GetMedia struct {
	Page Page `json:"page"`
	Media []Media `json:"media"`
}

type AddPartBody struct {
	Index int `json:"index"`
	Name string `json:"name"`
}

type EditCollectionBody struct {
	CollectionType *string `json:"collectionType,omitempty"`
	Name *string `json:"name,omitempty"`
	AdminStatus *string `json:"adminStatus,omitempty"`
}

type UpdateUserSettingsBody struct {
	DisplayName *string `json:"displayName,omitempty"`
}

type SetMediaUserData struct {
	List *string `json:"list,omitempty"`
	Score *int `json:"score,omitempty"`
	CurrentPart *int `json:"currentPart,omitempty"`
	RevisitCount *int `json:"revisitCount,omitempty"`
	IsRevisiting *bool `json:"isRevisiting,omitempty"`
}

type EditMediaBody struct {
	MediaType *string `json:"mediaType,omitempty"`
	TmdbId *string `json:"tmdbId,omitempty"`
	ImdbId *string `json:"imdbId,omitempty"`
	MalId *string `json:"malId,omitempty"`
	AnilistId *string `json:"anilistId,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Score *float32 `json:"score,omitempty"`
	Status *string `json:"status,omitempty"`
	Rating *string `json:"rating,omitempty"`
	AiringSeason *string `json:"airingSeason,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	AdminStatus *string `json:"adminStatus,omitempty"`
	Tags *[]string `json:"tags,omitempty"`
	Creators *[]string `json:"creators,omitempty"`
}

type GetNotifications struct {
	Page Page `json:"page"`
	Notifications []Notification `json:"notifications"`
}

type GetSystemInfo struct {
	Version string `json:"version"`
}

