// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api

type ProviderSupports struct {
	GetMedia bool `json:"getMedia"`
	SearchMedia bool `json:"searchMedia"`
	GetCollection bool `json:"getCollection"`
	SearchCollection bool `json:"searchCollection"`
}

type Provider struct {
	Name string `json:"name"`
	DisplayName string `json:"displayName"`
	Supports ProviderSupports `json:"supports"`
}

type ApiToken struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

type UserData struct {
	Id string `json:"id"`
	Username string `json:"username"`
	DisplayName *string `json:"displayName,omitempty"`
}

type MediaUser struct {
	HasData bool `json:"hasData"`
	List string `json:"list"`
	Score *int `json:"score,omitempty"`
	CurrentPart *int `json:"currentPart,omitempty"`
	RevisitCount *int `json:"revisitCount,omitempty"`
	IsRevisiting bool `json:"isRevisiting"`
}

type CreateMedia struct {
	Id string `json:"id"`
}

type CreateMediaBody struct {
	MediaType string `json:"mediaType"`
	Title string `json:"title"`
	Description string `json:"description"`
	Score float32 `json:"score"`
	Status string `json:"status"`
	Rating string `json:"rating"`
	AiringSeason string `json:"airingSeason"`
	StartDate string `json:"startDate"`
	EndDate string `json:"endDate"`
	PartCount int `json:"partCount"`
	CoverUrl string `json:"coverUrl"`
	BannerUrl string `json:"bannerUrl"`
	LogoUrl string `json:"logoUrl"`
	Tags []string `json:"tags"`
	Creators []string `json:"creators"`
	CollectionId string `json:"collectionId"`
	CollectionName string `json:"collectionName"`
}

type AddPart struct {
	Index int `json:"index"`
}

type SetMediaUserData struct {
	List *string `json:"list,omitempty"`
	Score *int `json:"score,omitempty"`
	CurrentPart *int `json:"currentPart,omitempty"`
	RevisitCount *int `json:"revisitCount,omitempty"`
	IsRevisiting *bool `json:"isRevisiting,omitempty"`
}

type AddCollectionItemBody struct {
	MediaId string `json:"mediaId"`
	Name string `json:"name"`
	SearchSlug string `json:"searchSlug"`
	Position int `json:"position"`
}

type GetMe struct {
	Id string `json:"id"`
	Username string `json:"username"`
	Role string `json:"role"`
	DisplayName string `json:"displayName"`
}

type EditMediaBody struct {
	MediaType *string `json:"mediaType,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Score *float32 `json:"score,omitempty"`
	Status *string `json:"status,omitempty"`
	Rating *string `json:"rating,omitempty"`
	AiringSeason *string `json:"airingSeason,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	AdminStatus *string `json:"adminStatus,omitempty"`
	Tags *[]string `json:"tags,omitempty"`
	Creators *[]string `json:"creators,omitempty"`
}

type EditPartBody struct {
	Name *string `json:"name,omitempty"`
}

type ProviderValue struct {
	Name string `json:"name"`
	DisplayName string `json:"displayName"`
	Value string `json:"value"`
}

type GetCollectionById struct {
	Id string `json:"id"`
	CollectionType string `json:"collectionType"`
	Name string `json:"name"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	Providers []ProviderValue `json:"providers"`
}

type ProviderSearchResult struct {
	ProviderName string `json:"providerName"`
	ProviderId string `json:"providerId"`
	Title string `json:"title"`
	ImageUrl string `json:"imageUrl"`
}

type GetProviderSearch struct {
	SearchResults []ProviderSearchResult `json:"searchResults"`
}

type ChangePasswordBody struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword string `json:"newPassword"`
	NewPasswordConfirm string `json:"newPasswordConfirm"`
}

type UpdateUserSettingsBody struct {
	DisplayName *string `json:"displayName,omitempty"`
}

type Page struct {
	Page int `json:"page"`
	PerPage int `json:"perPage"`
	TotalItems int `json:"totalItems"`
	TotalPages int `json:"totalPages"`
}

type Collection struct {
	Id string `json:"id"`
	CollectionType string `json:"collectionType"`
	Name string `json:"name"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	Providers []ProviderValue `json:"providers"`
}

type GetCollections struct {
	Page Page `json:"page"`
	Collections []Collection `json:"collections"`
}

type EditCollectionBody struct {
	CollectionType *string `json:"collectionType,omitempty"`
	Name *string `json:"name,omitempty"`
	AdminStatus *string `json:"adminStatus,omitempty"`
}

type GetProviders struct {
	Providers []Provider `json:"providers"`
}

type ProviderCollectionUpdateBody struct {
	ReplaceImages bool `json:"replaceImages"`
}

type GetSystemInfo struct {
	Version string `json:"version"`
}

type CollectionItem struct {
	CollectionId string `json:"collectionId"`
	MediaId string `json:"mediaId"`
	CollectionName string `json:"collectionName"`
	SearchSlug string `json:"searchSlug"`
	Position int `json:"position"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	MediaType string `json:"mediaType"`
	Score *float32 `json:"score,omitempty"`
	Status string `json:"status"`
	Rating string `json:"rating"`
	PartCount int `json:"partCount"`
	AiringSeason *string `json:"airingSeason,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	Creators []string `json:"creators"`
	Tags []string `json:"tags"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	User *MediaUser `json:"user,omitempty"`
}

type GetCollectionItems struct {
	Items []CollectionItem `json:"items"`
}

type EditCollectionItemBody struct {
	Name *string `json:"name,omitempty"`
	SearchSlug *string `json:"searchSlug,omitempty"`
	Position *int `json:"position,omitempty"`
}

type GetAllApiTokens struct {
	Tokens []ApiToken `json:"tokens"`
}

type MediaRelease struct {
	ReleaseType string `json:"releaseType"`
	StartDate string `json:"startDate"`
	NumExpectedParts int `json:"numExpectedParts"`
	PartOffset int `json:"partOffset"`
	IntervalDays int `json:"intervalDays"`
	DelayDays int `json:"delayDays"`
	Status string `json:"status"`
	CurrentPart int `json:"currentPart"`
	NextAiring *string `json:"nextAiring,omitempty"`
}

type Media struct {
	Id string `json:"id"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	MediaType string `json:"mediaType"`
	Score *float32 `json:"score,omitempty"`
	Status string `json:"status"`
	Rating string `json:"rating"`
	PartCount int `json:"partCount"`
	AiringSeason *string `json:"airingSeason,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	Creators []string `json:"creators"`
	Tags []string `json:"tags"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	Providers []ProviderValue `json:"providers"`
	User *MediaUser `json:"user,omitempty"`
	Release *MediaRelease `json:"release,omitempty"`
}

type GetMediaById struct {
	Id string `json:"id"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	MediaType string `json:"mediaType"`
	Score *float32 `json:"score,omitempty"`
	Status string `json:"status"`
	Rating string `json:"rating"`
	PartCount int `json:"partCount"`
	AiringSeason *string `json:"airingSeason,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate *string `json:"endDate,omitempty"`
	Creators []string `json:"creators"`
	Tags []string `json:"tags"`
	CoverUrl *string `json:"coverUrl,omitempty"`
	BannerUrl *string `json:"bannerUrl,omitempty"`
	LogoUrl *string `json:"logoUrl,omitempty"`
	Providers []ProviderValue `json:"providers"`
	User *MediaUser `json:"user,omitempty"`
	Release *MediaRelease `json:"release,omitempty"`
}

type MediaPart struct {
	Index int `json:"index"`
	MediaId string `json:"mediaId"`
	Name string `json:"name"`
}

type GetMediaParts struct {
	Parts []MediaPart `json:"parts"`
}

type AddPartBody struct {
	Index int `json:"index"`
	Name string `json:"name"`
}

type PartBody struct {
	Name string `json:"name"`
}

type SetPartsBody struct {
	Parts []PartBody `json:"parts"`
}

type SetMediaReleaseBody struct {
	MediaId string `json:"mediaId"`
	ReleaseType string `json:"releaseType"`
	StartDate string `json:"startDate"`
	NumExpectedParts int `json:"numExpectedParts"`
	IntervalDays int `json:"intervalDays"`
	DelayDays int `json:"delayDays"`
}

type CreateCollection struct {
	Id string `json:"id"`
}

type PostProviderImportMediaBody struct {
	Ids []string `json:"ids"`
}

type ProviderMediaUpdateBody struct {
	ReplaceImages bool `json:"replaceImages"`
}

type SignupBody struct {
	Username string `json:"username"`
	Password string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
}

type Signin struct {
	Token string `json:"token"`
}

type SigninBody struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type CreateApiToken struct {
	Token string `json:"token"`
}

type PostProviderImportCollectionsBody struct {
	Ids []string `json:"ids"`
}

type Signup struct {
	Id string `json:"id"`
	Username string `json:"username"`
}

type GetUser struct {
	Id string `json:"id"`
	Username string `json:"username"`
	DisplayName *string `json:"displayName,omitempty"`
}

type CreateApiTokenBody struct {
	Name string `json:"name"`
}

type GetMedia struct {
	Page Page `json:"page"`
	Media []Media `json:"media"`
}

type CreateCollectionBody struct {
	CollectionType string `json:"collectionType"`
	Name string `json:"name"`
}

